version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/todo
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "npx prisma migrate dev --name init && npm run dev"  # Добавляем команду для создания БД и запуска приложения

volumes:
  postgres-data:
